name: development-worklow

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'release/starbuck-v*'

jobs:

  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print variables
        run: |
          echo "CLAIM_CERTIFICATE: ${{ vars.CLAIM_CERTIFICATE }}"
  