name: development-worklow

on:
  push:
    branches:
      - 'release/starbuck-v*'

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print variables
        run: |
          echo "CLAIM_CERTIFICATE: ${{ vars.CLAIM_CERTIFICATE }}"
  