name: "Prepare, tag and generate a GitHub release for the code"

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  generate_tag_release:
    name: Generate tag and release for new version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Checkout code and submodule
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Retrieve previous tag (when triggered manually)
        id: previous_tag
        run: |
          previous_tag=$(git tag --list "floac-v*" --sort=-version:refname | head -1)
          echo "Using previous tag ${previous_tag}"
          # Strip "floac-v" prefix
          version=${previous_tag:7}
          echo "Previous version: ${version}"
          echo "${version}" > $GITHUB_WORKSPACE/VERSION

          echo "previous_tag=${previous_tag}" >> $GITHUB_OUTPUT
          echo "previous_version=${previous_version}" >> $GITHUB_OUTPUT

      - name: Configure git
        run: |
          git config --global --add safe.directory "*"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Retrieve current version
        id: retrieve_version
        run: |
          version=$(grep -oP 'VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "Current version: ${version}"
          echo "current_version=${version}" >> $GITHUB_ENV
          tag="floac-v${version}"
          echo "version=${version}" >>"$GITHUB_OUTPUT"
          echo "TAG=${tag}" >> "$GITHUB_ENV"
          git tag -a "${tag}" -m "Release floAC ${tag}"
          git push origin "${tag}"
          echo "github commit -> ${GITHUB_SHA}"

      - name: Update latest tag
        id: updateLatest
        run: | 
          highest_version_tag=$(git tag --list "floac-v*" --sort=-version:refname | head -1)
          highest_version_commit=$(git rev-list -n 1 ${highest_version_tag})

          if [ "${GITHUB_SHA}" == "$highest_version_commit" ]; then
            git tag -f floac-latest
            git push -f origin floac-latest
            echo "floac-latest tag moved from ${highest_version_tag} to ${TAG}"
          else
            echo "no floac-latest tag update required"
          fi
        env:
          TAG: ${{ env.TAG }}

      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ steps.previous_tag.outputs.previous_tag }}
          excludeTags: "floac-latest"
          repo: ${{ github.repository }}
          output: release.md
        env:
          TAG: ${{ env.TAG }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "release.md"
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger tag workflow
        run: |
          gh workflow run build.yml --ref ${{ env.TAG }}
        env:
          GH_TOKEN: ${{ github.token }}
