name: development-worklow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'release/starbuck*'

jobs:

  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print variables
        run: |
          echo "CLAIM_CERTIFICATE: ${{ vars.CLAIM_CERTIFICATE }}"

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip --junk-paths my-artifact README.md